name: quill_js
publish_to: none
version: 1.0.0
description: Quill JS for Quire
homepage: https://quire.io
repository: https://github.com/quire-io/quill_js
issue_tracker: https://github.com/quire-io/quill_js/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  js: ^0.7.1

dev_dependencies:
  lints: ^4.0.0
